### ISSUE TITLE
onAuthenticated ID:0

### ISSUE THREAD

**Issue by alex9yust** [Evolution-X-AOSP/frameworks_base#199]
https://github.com/Evolution-X/frameworks_base/blob/649b92ab54574645f7c45fff527f827fea81a91f/services/core/java/com/android/server/biometrics/AuthenticationClient.java#L159

unofficial build for alioth
config_powerButtonFingerprint := true

After several consecutive unlocks with a registered finger, if press with
an unregistered finger, sometimes the screen is unlocked. while in the logs ID:0.

07-11 18:44:53.872  1272  1599 W android.hardware.biometrics.fingerprint@2.1-service: onAuthenticated(fid=0, gid=0)
07-11 18:44:53.873  1569  1569 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@649763a, requireConfirmation: false, user: 0
07-11 18:44:54.269  1272  1598 W android.hardware.biometrics.fingerprint@2.1-service: onAcquired(6) (23)
07-11 23:23:14.803     0     0 I fpc1020 soc: fingerprint_fpc: fingerdown_wait_set -> enable
07-11 18:44:55.259  1272  1599 W android.hardware.biometrics.fingerprint@2.1-service: onAcquired(6) (22)
07-11 23:23:15.723     0     0 I fpc1020 soc: fingerprint_fpc: fingerdown_wait_set -> disable
07-11 18:44:55.570  1272  1599 W android.hardware.biometrics.fingerprint@2.1-service: onAcquired(0) (0)

solution for myself: https://github.com/alex9yust/frameworks_base/commit/a19c17c7f693a2437e341f7f0a737822415c0130

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/frameworks_base/commit/ed35d6ebcdbc2a49c8f0e3e2a3f28f7b78a1bf4c

Maybe you can check this commit and see if anything's amiss.

**Comment by alex9yust** [comment]
> Maybe you can check this commit and see if anything's amiss.

Ok, maybe I took the example from the logs incorrectly
07-03 15:47:11.779  1642  1642 V FingerprintService: onAuthenticated(true), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@2097d58, requireConfirmation: false, user: 0

this is better?

**Comment by Stallix** [comment]
I guess since it sees the previous attempts as onAuthenticated(true), it's still able to unlock? However I don't experience this problem on an FOD device. Maybe it's something with your implementation device side?

**Comment by joeyhuab** [comment]
> > Maybe you can check this commit and see if anything's amiss.
> 
> Ok, maybe I took the example from the logs incorrectly
> 07-03 15:47:11.779 1642 1642 V FingerprintService: onAuthenticated(true), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@2097d58, requireConfirmation: false, user: 0
> 
> this is better?

I guess since it sees the previous attempts as onAuthenticated(true), it's still able to unlock? However I don't experience this problem on an FOD device. Maybe it's something with your implementation device side?

**Comment by alex9yust** [comment]
in general, I saw this only when I added config_powerButtonFingerprint: = true and switched it so that the scanner was triggered when the power button was pressed. before that, I have not seen any errors when the scanner worked on touch.
and I don't know why this happens, rarely, but it happens.
therefore such a crutch.

one case out of ~20, although sometimes it happens more often

07-12 10:42:07.447  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@944b45, requireConfirmation: false, user: 0
07-12 10:42:12.352  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@b61ad69, requireConfirmation: false, user: 0
07-12 10:42:13.516  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@b61ad69, requireConfirmation: false, user: 0
07-12 10:42:25.615  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@856e9df, requireConfirmation: false, user: 0
07-12 10:42:28.768  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@2e1e363, requireConfirmation: false, user: 0
07-12 10:42:39.738  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@f21b4cd, requireConfirmation: false, user: 0
07-12 10:42:43.853  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@fa358ea, requireConfirmation: false, user: 0
07-12 10:42:49.491  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@5e6a82a, requireConfirmation: false, user: 0
07-12 10:42:55.324  1623  1623 V FingerprintService: **onAuthenticated(true), ID:0**, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@aef4fcf, requireConfirmation: false, user: 0
07-12 10:43:34.399  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@c5a2890, requireConfirmation: false, user: 0
07-12 10:43:54.200  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@9216735, requireConfirmation: false, user: 0
07-12 10:44:06.550  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@2d496e8, requireConfirmation: false, user: 0
07-12 10:44:19.283  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@f5f59f6, requireConfirmation: false, user: 0
07-12 10:44:27.848  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@5188c00, requireConfirmation: false, user: 0
07-12 10:44:41.744  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@888ef5, requireConfirmation: false, user: 0
07-12 10:44:47.921  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@95e903f, requireConfirmation: false, user: 0
07-12 10:44:55.807  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@5d1ca34, requireConfirmation: false, user: 0
07-12 10:45:01.483  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@773c442, requireConfirmation: false, user: 0
07-12 10:45:09.258  1623  1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@d1c8529, requireConfirmation: false, user: 0

**Comment by joeyhuab** [comment]
> in general, I saw this only when I added config_powerButtonFingerprint: = true and switched it so that the scanner was triggered when the power button was pressed. before that, I have not seen any errors when the scanner worked on touch.
> and I don't know why this happens, rarely, but it happens.
> therefore such a crutch.
> 
> one case out of ~20, although sometimes it happens more often
> 
> 07-12 10:42:07.447 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@944b45, requireConfirmation: false, user: 0
> 07-12 10:42:12.352 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@b61ad69, requireConfirmation: false, user: 0
> 07-12 10:42:13.516 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@b61ad69, requireConfirmation: false, user: 0
> 07-12 10:42:25.615 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@856e9df, requireConfirmation: false, user: 0
> 07-12 10:42:28.768 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@2e1e363, requireConfirmation: false, user: 0
> 07-12 10:42:39.738 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@[f21b4cd](https://github.com/Evolution-X/frameworks_base/commit/f21b4cde1865747ed054111944e6b30e38109293), requireConfirmation: false, user: 0
> 07-12 10:42:43.853 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@fa358ea, requireConfirmation: false, user: 0
> 07-12 10:42:49.491 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@5e6a82a, requireConfirmation: false, user: 0
> 07-12 10:42:55.324 1623 1623 V FingerprintService: **onAuthenticated(true), ID:0**, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@aef4fcf, requireConfirmation: false, user: 0
> 07-12 10:43:34.399 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@c5a2890, requireConfirmation: false, user: 0
> 07-12 10:43:54.200 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@9216735, requireConfirmation: false, user: 0
> 07-12 10:44:06.550 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@2d496e8, requireConfirmation: false, user: 0
> 07-12 10:44:19.283 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@f5f59f6, requireConfirmation: false, user: 0
> 07-12 10:44:27.848 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@5188c00, requireConfirmation: false, user: 0
> 07-12 10:44:41.744 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@888ef5, requireConfirmation: false, user: 0
> 07-12 10:44:47.921 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@95e903f, requireConfirmation: false, user: 0
> 07-12 10:44:55.807 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@5d1ca34, requireConfirmation: false, user: 0
> 07-12 10:45:01.483 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@773c442, requireConfirmation: false, user: 0
> 07-12 10:45:09.258 1623 1623 V FingerprintService: onAuthenticated(false), ID:0, Owner: com.android.systemui, isBP: false, listener: com.android.server.biometrics.fingerprint.FingerprintService$ServiceListenerImpl@d1c8529, requireConfirmation: false, user: 0

I don't see any issues with https://github.com/Evolution-X/frameworks_base/commit/dd8b9f9be3ad3ad3f4af6da456e80f97361605df as well. Hmm we'll see for now.

**Comment by joeyhuab** [comment]
Not enough info on the issue itself so I'm closing this.
