### ISSUE TITLE
AutoBrightness in QS?

### ISSUE THREAD

**Issue by alex9yust** [Evolution-X-AOSP/frameworks_base#237]
from https://github.com/NusantaraProject-ROM/android_frameworks_base/commit/2bd7a88bbbd6dbad19c8ff568cc30cfdee02b39d#diff-83273a20f05f520a998d1d268764d0ec9
c631bfe97191dab66d8da305b76723f

patch https://drive.google.com/file/d/1rMxOtfcyLVgCJcqf7b0qLzSwXLT0SzOt/view?usp=sharing

png https://drive.google.com/file/d/1ONOIYXZ7iHZGqJn86Y-K-S9lHdhkdZPJ/view?usp=sharing

**Comment by joeyhuab** [comment]
Too much changes. Won't add unless you make a proper PR in frameworks_base and Evolver.

**Comment by soumya19x** [comment]
> Too much changes. Won't add unless you make a proper PR in frameworks_base and Evolver.

Can you add left volume panel overlay - https://github.com/DerpFest-11/frameworks_base/commit/515e9a2cc8625122d10d2f5e478ffa36f83d0287

**Comment by joeyhuab** [comment]
> from [NusantaraProject-ROM/android_frameworks_base@2bd7a88#diff-83273a20f05f520a998d1d268764d0ec9](https://github.com/NusantaraProject-ROM/android_frameworks_base/commit/2bd7a88bbbd6dbad19c8ff568cc30cfdee02b39d#diff-83273a20f05f520a998d1d268764d0ec9) c631bfe97191dab66d8da305b76723f
> 
> patch [drive.google.com/file/d/1rMxOtfcyLVgCJcqf7b0qLzSwXLT0SzOt/view?usp=sharing](https://drive.google.com/file/d/1rMxOtfcyLVgCJcqf7b0qLzSwXLT0SzOt/view?usp=sharing)
> 
> png [drive.google.com/file/d/1ONOIYXZ7iHZGqJn86Y-K-S9lHdhkdZPJ/view?usp=sharing](https://drive.google.com/file/d/1ONOIYXZ7iHZGqJn86Y-K-S9lHdhkdZPJ/view?usp=sharing)

Added: https://github.com/Evolution-X/frameworks_base/commit/299d7132f1d7a628e7d9ac56fe1f482b80d3b4aa
Part 2: https://github.com/Evolution-X/frameworks_base/commit/b4400a2ab4a78eeb67c03639a657438bb8497e78

**Comment by joeyhuab** [comment]
> > Too much changes. Won't add unless you make a proper PR in frameworks_base and Evolver.
> 
> Can you add left volume panel overlay - [DerpFest-11/frameworks_base@515e9a2](https://github.com/DerpFest-11/frameworks_base/commit/515e9a2cc8625122d10d2f5e478ffa36f83d0287)

https://github.com/Evolution-X/frameworks_base/commit/818dfa2612091133ffc60debe22b7ed6a358e7d3

Added. Issue closed.
