### ISSUE TITLE
Revert "base: return a boolean instead of KeyEvent in handleKeyEvent"

### ISSUE THREAD

**Issue by soumya19x** [Evolution-X-AOSP/frameworks_base#238]
https://github.com/PixelPlusUI-SnowCone/frameworks_base/commit/808a24f0659cc22ae1307aeb6fd04c507a1127a6

**Comment by joeyhuab** [comment]
> [PixelPlusUI-SnowCone/frameworks_base@808a24f](https://github.com/PixelPlusUI-SnowCone/frameworks_base/commit/808a24f0659cc22ae1307aeb6fd04c507a1127a6)

And? We don't have the same error when compiling the ROM. Just because some other ROM reverted, doesn't mean we have to.
