### ISSUE TITLE
Monet -Icon Color displayed in the preview not matching with homescreen icons.

### ISSUE THREAD

**Issue by naveenbank1380** [Evolution-X-AOSP/frameworks_base#241]
When I tried changing various wallpapers , For few walls, color displayed in the previews did not match the homescreen icons.

To regain color back, i had to use Green colored wallpaper in between.

Attached few screenshots.

![Screenshot_20220119-224436_Wallpaper   style](https://user-images.githubusercontent.com/98048201/150191606-df527e88-46cc-4144-b1d9-28f4e5952cc4.png)

Preview mode
 
![Screenshot_20220119-224441_Pixel Launcher](https://user-images.githubusercontent.com/98048201/150191671-efbafc19-d7f3-4a2e-a0fd-8e54d8f2974d.png)
After applying wallpaper
#
![d45f057a-0764-4dbe-8a9f-33ca2ee2763c](https://user-images.githubusercontent.com/98048201/150192158-7d0ac30b-b6e3-4a81-a4b1-d44c8bd3dbbd.jpg)
![a4550588-3da9-42c2-b12b-88d2aa958c92](https://user-images.githubusercontent.com/98048201/150192173-4f8889b3-965e-4f7d-a013-70ceaa9f7648.jpg)

**Comment by naveenbank1380** [comment]
@Stallix It is happening on latest Evolution x build dated 1801 _Alioth device. I can provide more details if needed

**Comment by joeyhuab** [comment]
A force stop fixes the app completely.
