### ISSUE TITLE
Add support for camera keys?

### ISSUE THREAD

**Issue by Cheng171** [Evolution-X-AOSP/frameworks_base#279]
My phone has physical camera key, and the device tree is configured correctly, but camera key is not displayed in the hardware keys interface.

**Comment by joeyhuab** [comment]
> My phone has physical camera key, and the device tree is configured correctly, but camera key is not displayed in the hardware keys interface.

Don't even know which commit you are talking about.

**Comment by DeanWinchesterrr** [comment]
That is what will happen if you Kang every second of your life.
