### ISSUE TITLE
Add support for dynamic volte icon

### ISSUE THREAD

**Issue by YaLex69** [Evolution-X-AOSP/frameworks_base#309]
Sir please add dynamic volte icon it will save some notch space

https://gitlab.com/xkaen/framework_base/-/commit/0b6bb562861e51d5b9d81d45c28dd07061a075ca
https://gitlab.com/xkaen/framework_base/-/commit/38853c0931d0464bcb16376e35b8b3c672a33fde
https://gitlab.com/xkaen/framework_base/-/commit/fdb5560b9f0475cecd4191707103dda2333245e4

https://github.com/NAMELESS-AOSP-OPENSOURCE?tab=repositories

**Comment by joeyhuab** [comment]
> Sir please add dynamic volte icon it will save some notch space
> 
> [gitlab.com/xkaen/framework_base/-/commit/0b6bb562861e51d5b9d81d45c28dd07061a075ca](https://gitlab.com/xkaen/framework_base/-/commit/0b6bb562861e51d5b9d81d45c28dd07061a075ca) [gitlab.com/xkaen/framework_base/-/commit/38853c0931d0464bcb16376e35b8b3c672a33fde](https://gitlab.com/xkaen/framework_base/-/commit/38853c0931d0464bcb16376e35b8b3c672a33fde) [gitlab.com/xkaen/framework_base/-/commit/fdb5560b9f0475cecd4191707103dda2333245e4](https://gitlab.com/xkaen/framework_base/-/commit/fdb5560b9f0475cecd4191707103dda2333245e4)
> 
> [@NAMELESS-AOSP-OPENSOURCE?tab=repositories](https://github.com/NAMELESS-AOSP-OPENSOURCE?tab=repositories)

How is this an "issue?"
