### ISSUE TITLE
[BUG] Navigation pill not aligned properly 

### ISSUE THREAD

**Issue by ArberTu474** [Evolution-X-AOSP/frameworks_base#323]
This bug was present in the latest update of evolution x (Eve-7.1-sweet-20220906-1901-OFFICIAL). I am using a redmi note 10 pro.

A screenshot of the problem
![Screenshot_20220909-171816_Chrome](https://user-images.githubusercontent.com/88089607/189409214-ec98d5d6-d01c-4f49-bbf0-0c6d21e94d82.png)

**Comment by joeyhuab** [comment]
Yeah thanks for spamming. It was already solved with the removal of the burn in commit.
