### ISSUE TITLE
Lock screen crash on reboot

### ISSUE THREAD

**Issue by Yurab0b** [Evolution-X-AOSP/frameworks_base#329]
### POCO X3 PRO, Evolution X 7.1, magisk 25.2
When i reboot my phone it crashes on the lock screen (turns on, shows wallpaper and time, turns off the screen, tries again) ~5 times until it reboots to do the same thing again
After it reboots it does the same thing again but when it reboots the second time it boots to recovery (OrangeFox) with errors in the log
```
Android Rescue Party trigger! Possible solutions? Either:
 1. Wipe caches, and/or
 2. Format data, and/or
 3. Clean-flash your ROM.
 
The reported problem is:
 '--reason=RescueParty'
```
Full log of that OrangeFox load here: [recovery_20220912_212822[2].log](https://github.com/Evolution-X/frameworks_base/files/9551705/recovery_20220912_212822.2.log)

Somehow i was able to fix this by plugging in a USB cable during boot because i was trying to get adb logs.
This bug has actually happened to me twice, the first time i thought it was a lucky patcher bug (patching android), i just didn't think much of it, just wiped /data and continued onwards, but this time i didnt flash anything except the rom and magisk 25.2 stable
If you want any additional logs/details just reply to this issue

**Edit: after a few reboots even this work around with the usb cable stopped working**

**Comment by joeyhuab** [comment]
Was already solved after https://github.com/Evolution-X/frameworks_base/commit/8f760aa2e6cf2d0ac59107ec7df22dad938a48f0
