### ISSUE TITLE
SystemUI crash on boot when i have a SIM card installed.

### ISSUE THREAD

**Issue by Gontier-Julien** [Evolution-X-AOSP/frameworks_base#336]
Still had the same issue with it...
It is **A FRESH INSTALL**

And it just spam the logs with this like 100x time.

https://pastebin.com/1VWn4LSE

https://pastebin.com/yuRdtXbH

https://pastebin.com/2uZ3TnEy

The current "fix" for it is to just remove my SIM card.

**Comment by Gontier-Julien** [comment]
Disabling Sim toolkit seems to help the systemUI to stop freaking out because it does this:

Phone start > systemui pop up > systemui gone > systemui pop up > systemui gone > etc...etc... until it stabilize it self and/or reboot the whole phone

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/frameworks_base/commit/5703ea76963efb03afbe51689a77cfd3d938a8aa

Should be fixed with this based on your logs.

**Comment by Gontier-Julien** [comment]
> [5703ea7](https://github.com/Evolution-X/frameworks_base/commit/5703ea76963efb03afbe51689a77cfd3d938a8aa)
> 
> Should be fixed with this based on your logs.

Hope it would i'll close this issue if it is fixed on the next update

**Comment by joeyhuab** [comment]
> > [5703ea7](https://github.com/Evolution-X/frameworks_base/commit/5703ea76963efb03afbe51689a77cfd3d938a8aa)
> > Should be fixed with this based on your logs.
> 
> Hope it would i'll close this issue if it is fixed on the next update

Kindly disable SIM pin for now. That's what's causing the issue.

**Comment by joeyhuab** [comment]
> > [5703ea7](https://github.com/Evolution-X/frameworks_base/commit/5703ea76963efb03afbe51689a77cfd3d938a8aa)
> > Should be fixed with this based on your logs.
> 
> Hope it would i'll close this issue if it is fixed on the next update

https://github.com/Evolution-X/frameworks_base/commit/1d7e27e3bc8834f3a983acecae488f6933e152e0

Can confirm fixed on the latest.

**Comment by Gontier-Julien** [comment]
> > > [5703ea7](https://github.com/Evolution-X/frameworks_base/commit/5703ea76963efb03afbe51689a77cfd3d938a8aa)
> > > Should be fixed with this based on your logs.
> > 
> > 
> > Hope it would i'll close this issue if it is fixed on the next update
> 
> [1d7e27e](https://github.com/Evolution-X/frameworks_base/commit/1d7e27e3bc8834f3a983acecae488f6933e152e0)
> 
> Can confirm fixed on the latest.

Nice, and unfortunately i cannot disable the pin on my SIM card it is required, so i'll just pop it out for now ^^

**Comment by Gontier-Julien** [comment]
> > > [5703ea7](https://github.com/Evolution-X/frameworks_base/commit/5703ea76963efb03afbe51689a77cfd3d938a8aa)
> > > Should be fixed with this based on your logs.
> > 
> > 
> > Hope it would i'll close this issue if it is fixed on the next update
> 
> [1d7e27e](https://github.com/Evolution-X/frameworks_base/commit/1d7e27e3bc8834f3a983acecae488f6933e152e0)
> 
> Can confirm fixed on the latest.

So if i do this [OTA update](https://github.com/Evolution-X-Devices/official_devices/blob/master/changelogs/instantnoodle/evolution_instantnoodle-ota-tp1a.220905.004.a2-09270622-unsigned.zip.txt) it should be fixed then right?

**Comment by Gontier-Julien** [comment]
Alright i did the last OTA update, it can boot without panic with the SIM card in thank a lot!!

I still got some log that the systemui produce, but everything seem to be working as excepted ^^
I"m just going to share it just in case :

https://pastebin.com/fGE8h1Fn

https://pastebin.com/Jed4kT47

https://pastebin.com/dSzNFpLV

https://pastebin.com/aHn9jebb

**Comment by joeyhuab** [comment]
> Alright i did the last OTA update, it can boot without panic with the SIM card in thank a lot!!
> 
> I still got some log that the systemui produce, but everything seem to be working as excepted ^^ I"m just going to share it just in case :
> 
> [pastebin.com/fGE8h1Fn](https://pastebin.com/fGE8h1Fn)
> 
> [pastebin.com/Jed4kT47](https://pastebin.com/Jed4kT47)
> 
> [pastebin.com/dSzNFpLV](https://pastebin.com/dSzNFpLV)
> 
> [pastebin.com/aHn9jebb](https://pastebin.com/aHn9jebb)

Those logs are unrelated to the main issue. Closing this.

**Comment by Gontier-Julien** [comment]
> > Alright i did the last OTA update, it can boot without panic with the SIM card in thank a lot!!
> > I still got some log that the systemui produce, but everything seem to be working as excepted ^^ I"m just going to share it just in case :
> > [pastebin.com/fGE8h1Fn](https://pastebin.com/fGE8h1Fn)
> > [pastebin.com/Jed4kT47](https://pastebin.com/Jed4kT47)
> > [pastebin.com/dSzNFpLV](https://pastebin.com/dSzNFpLV)
> > [pastebin.com/aHn9jebb](https://pastebin.com/aHn9jebb)
> 
> Those logs are unrelated to the main issue. Closing this.

Should i reopen a new issue for those?
