### ISSUE TITLE
SystemUI crash on boot when a SIM card installed AGAIN + others funky ui stuff

### ISSUE THREAD

**Issue by Gontier-Julien** [Evolution-X-AOSP/frameworks_base#341]
Still the same issue **exactly the same as #336** with the [latest build](https://github.com/Evolution-X-Devices/official_devices/blob/master/changelogs/instantnoodle/evolution_instantnoodle-ota-tp1a.220905.004.a2-09302348-unsigned.zip.txt)

Did a full clean install to test it, and yet again it is there, latest build was working just fine with the fix...

**Comment by Gontier-Julien** [comment]
I'll drop the logs there for good mesure:

https://pastebin.com/LEpx2HaX

https://pastebin.com/qyrGNGHR

https://pastebin.com/5hqkYUX6

**Comment by Gontier-Julien** [comment]
Also the daily data usage toggle isn't even on and i think (with my understanding of what is happening) that something very wrong is happening with it.

**Comment by Gontier-Julien** [comment]
Also when doing some test, the systemui restart (with the power menu) sometimes take ages and rarely reboot the whole phone.

Here is the log that i have:

https://pastebin.com/7T8mzdzz

**Comment by joeyhuab** [comment]
man i'm so tired of this bullshit

**Comment by AnierinBliss** [comment]
It's sim pin that's causing issues with it. You don't need the toggle for qs footer data usage enabled to trigger this. Anyways, it's being removed, now cope and wait. In the meantime, disable your sim pin!!!

**Comment by Gontier-Julien** [comment]
First don't need to be mean i'm just reporting a bug..., secondly i am not the only one to have this issue too... Thirdly if some user have they're sim pin enable it for a personal reason, and it shouldn't break it self like that.
I know you guys are doing a lots of hard work over here to get this rom going for lots of devices and i'm grateful for it, and i'm okay to do temporary stuff to fix a "stupid" bug, but if a bug like this come on multiple user devices, you can't just tell all of them to just remove it for "x" numbers of update, one is fine but not for 40 (exaggerated) update or so, and especially if it bootloop they're devices.
And i know there a lots of other stupid bugs to fix because android 13 just came out and google do some funky stuff with they're code and i understand that you have to work on it as well.
Anyways i've removed the pin now...
