### ISSUE TITLE
[feature request] allow setting auto rotation angles

### ISSUE THREAD

**Issue by TobiPeterG** [Evolution-X-AOSP/frameworks_base#347]
Hey there,

it would be nice if the user was able to select which angles the phone is allowed to rotate to when auto rotation is activated.
Relevant commits could be:
https://github.com/crdroidandroid/android_frameworks_base/commit/4191994d847c634e0997070ae723e91385c99b94

https://github.com/crdroidandroid/android_frameworks_base/commit/b5b859a5b292534ce9514b9a86f2e4d066c20a34

**Comment by AnierinBliss** [comment]
Pretty sure this also requires additions to packages/apps/Settings. Although, feel free to make these changes and submit a PR rather than linking commits.
