### ISSUE TITLE
Navigation Pill isn't properly aligned

### ISSUE THREAD

**Issue by fernandosang** [Evolution-X-AOSP/frameworks_base#357]
I read another issue saying it was already fixed, but it's not. I'm using Oneplus 8's build and the problem is still there.

Great ROM but this is just obnoxious
![189409214-ec98d5d6-d01c-4f49-bbf0-0c6d21e94d82](https://user-images.githubusercontent.com/77039486/200604887-cddaa8c5-36cc-4c29-afab-3f17a2099b9e.png)

**Comment by joeyhuab** [comment]
Feel free to flash another ROM. :)

**Comment by fernandosang** [comment]
No wonder the ROM is so mediocre. The dev is just the same lol
