### ISSUE TITLE
Crash when trying to edit QS

### ISSUE THREAD

**Issue by alex9yust** [Evolution-X-AOSP/frameworks_base#363]
https://github.com/Evolution-X/frameworks_base/blob/4d93cd6ec9c290a822ca5cc88130a4f1bb509519/packages/SystemUI/src/com/android/systemui/qs/QSTileHost.java#L403

--------- beginning of crash
12-13 16:00:53.629  2161  2161 E AndroidRuntime: FATAL EXCEPTION: main
12-13 16:00:53.629  2161  2161 E AndroidRuntime: Process: com.android.systemui, PID: 2161
12-13 16:00:53.629  2161  2161 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boole
an java.lang.String.startsWith(java.lang.String)' on a null object reference
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.QSTileHost.removeTile(QSTileHost.java
:2)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.tiles.AntiFlickerTile.updateConfig(An
tiFlickerTile.java:28)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.tiles.AntiFlickerTile.<init>(AntiFlic
kerTile.java:30)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.tiles.AntiFlickerTile_Factory.get(Ant
iFlickerTile_Factory.java:75)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.tileimpl.QSFactoryImpl.createTile(QSF
actoryImpl.java:1222)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.QSTileHost.createTile(QSTileHost.java
:17)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.customize.QSCustomizerController.show
(QSCustomizerController.java:343)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.systemui.qs.QSPanelController$$ExternalSyntheticL
ambda0.run(R8$$SyntheticClass:601)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7868)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(R
untimeInit.java:548)
12-13 16:00:53.629  2161  2161 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

if (spec != null) {
...
}

**Comment by joeyhuab** [comment]
Great, you also caught it. So what's the solution then?

**Comment by alex9yust** [comment]
check spec != null
```

index 3bf867a31da1..62dca352fd2a 100644
--- a/packages/SystemUI/src/com/android/systemui/qs/QSTileHost.java
+++ b/packages/SystemUI/src/com/android/systemui/qs/QSTileHost.java
@@ -401,12 +401,13 @@ public class QSTileHost implements QSHost, Tunable, PluginListener<QSFactory>, D
      */
     @Override
     public void removeTile(String spec) {
-        if (spec.startsWith(CustomTile.PREFIX)) {
+        if (spec != null && spec.startsWith(CustomTile.PREFIX)) {
             // If the tile is removed (due to it not actually existing), mark it as removed. That
             // way it will be marked as newly added if it appears in the future.
             setTileAdded(CustomTile.getComponentFromSpec(spec), mCurrentUser, false);
         }
-        mMainExecutor.execute(() -> changeTileSpecs(tileSpecs-> tileSpecs.remove(spec)));
+        if (spec != null)
+            mMainExecutor.execute(() -> changeTileSpecs(tileSpecs-> tileSpecs.remove(spec)));
     }
.
     /**


```

**Comment by alex9yust** [comment]
I did not look above why null gets there

**Comment by joeyhuab** [comment]
> check spec != null
> 
> ```
> 
> index 3bf867a31da1..62dca352fd2a 100644
> --- a/packages/SystemUI/src/com/android/systemui/qs/QSTileHost.java
> +++ b/packages/SystemUI/src/com/android/systemui/qs/QSTileHost.java
> @@ -401,12 +401,13 @@ public class QSTileHost implements QSHost, Tunable, PluginListener<QSFactory>, D
>       */
>      @Override
>      public void removeTile(String spec) {
> -        if (spec.startsWith(CustomTile.PREFIX)) {
> +        if (spec != null && spec.startsWith(CustomTile.PREFIX)) {
>              // If the tile is removed (due to it not actually existing), mark it as removed. That
>              // way it will be marked as newly added if it appears in the future.
>              setTileAdded(CustomTile.getComponentFromSpec(spec), mCurrentUser, false);
>          }
> -        mMainExecutor.execute(() -> changeTileSpecs(tileSpecs-> tileSpecs.remove(spec)));
> +        if (spec != null)
> +            mMainExecutor.execute(() -> changeTileSpecs(tileSpecs-> tileSpecs.remove(spec)));
>      }
> .
>      /**
> ```

Try with e18b8bd6da9ae0006e734d54792717573d28c45e.
