### ISSUE TITLE
Slow system on Redmi Note 10 Pro

### ISSUE THREAD

**Issue by BidibulleKing** [Evolution-X-AOSP/frameworks_base#366]
Hi! I did the last update on Xiaomi Redmi Note 10 Pro. Since, the system (not when I'm on an app) is extremely slow...
When I reboot my phone, all is okay, but after 5-10 minutes: it's slow again.

Furthermore, I have like "screen refresh" (my screen goes black for half a second then return to normal).

Can those problems be solved?

**Comment by joeyhuab** [comment]
This is not a GENERAL ROM issue. Not all devices are AFFECTED by this slow system issue. Report to your MAINTAINER DIRECTLY.
