### ISSUE TITLE
[feature request] add QS background transparency

### ISSUE THREAD

**Issue by TobiPeterG** [Evolution-X-AOSP/frameworks_base#410]
Hey there,

Crdroid already supports transparent QS background and it might be a fine addition to EvoX as well. It doesn't need a restart of system UI but is applied instantly and works perfectly fine.

Here is the relevant commits (I tried to find all, but I'm not quite sure if this is the only one required):
https://github.com/crdroidandroid/android_frameworks_base/commit/2c319bd2904704e329e8d4d2befa7da1da58ba45

For the settings app, a commit like this is required:
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/4322653a828dbd9093afe79f32cc81cea73fa16e

**Comment by Stallix** [comment]
Set theme to light then lock the device. Open the lockscreen but don't unlock, swipe down from status bar and see QS panel. You'll see why this isn't being added.

**Comment by joeyhuab** [comment]
> Hey there,
> 
> Crdroid already supports transparent QS background and it might be a fine addition to EvoX as well. It doesn't need a restart of system UI but is applied instantly and works perfectly fine.
> 
> Here is the relevant commits (I tried to find all, but I'm not quite sure if this is the only one required): [crdroidandroid/android_frameworks_base@2c319bd](https://github.com/crdroidandroid/android_frameworks_base/commit/2c319bd2904704e329e8d4d2befa7da1da58ba45)
> 
> For the settings app, a commit like this is required: [crdroidandroid/android_packages_apps_crDroidSettings@4322653](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/4322653a828dbd9093afe79f32cc81cea73fa16e)

It's not that I'm unaware.

Set theme to light then lock the device. Open the lockscreen but don't unlock, swipe down from status bar and see QS panel. You'll see why this isn't being added.

**Comment by TobiPeterG** [comment]
Thank you for your answer, I did just that, but all I saw was a QS panel with a black bsckground. Am I missing something?
I switched to light theme beforehand.

Their implementation also supports dark themes. So this might be an advantage. :)

**Comment by joeyhuab** [comment]
> Thank you for your answer, I did just that, but all I saw was a QS panel with a black bsckground. Am I missing something? I switched to light theme beforehand.
> 
> Their implementation also supports dark themes. So this might be an advantage. :)

Are you SURE you didn't add the LIGHT QS support first before adding this? BECAUSE IT IS REQUIRED to make it work properly like you said. Can't believe I have to make a test build just to prove my point.

**Comment by TobiPeterG** [comment]
Umm I literally installed EvoX on another device, booted it, skipped the setup, set the theme to light and checked the lock screen.
It's an official EvoX device with a build from Feb 25th
Have I done something wrong?

**Comment by joeyhuab** [comment]
> Umm I literally installed EvoX on another device, booted it, skipped the setup, set the theme to light and checked the lock screen. It's an official EvoX device with a build from Feb 25th Have I done something wrong?

And you're doing all the checking WITH THE QS TRANSPARENCY stuff or WITHOUT IT?

**Comment by joeyhuab** [comment]
![photo_2023-02-28_20-53-10](https://user-images.githubusercontent.com/6667815/221860328-0835099a-700c-4388-a11a-f40f6a618808.jpg)
I hope THIS MAKES YOU UNDERSTAND.
