### ISSUE TITLE
Small render issue in Qs tile

### ISSUE THREAD

**Issue by marinoalfonz1** [Evolution-X-AOSP/frameworks_base#436]
A small render time is taken when the qs is expanded fully.. During the render time it is not possible to switch the qs tiles pages.. 

Observe the colour change in the wifi and Mobile data tile when the qs is expanded

https://github.com/Evolution-X/frameworks_base/assets/85938685/1b237f61-19a8-4f56-8d70-14b5fd652277

**Comment by joeyhuab** [comment]
> A small render time is taken when the qs is expanded fully.. During the render time it is not possible to switch the qs tiles pages..
> 
> Observe the colour change in the wifi and Mobile data tile when the qs is expanded
> 
>  5_6267118623651792980.mp4

That's not a render issue. That's a fade filter added when using QS header images.

https://github.com/Evolution-X/frameworks_base/commit/844b63141621f0cecaa410298d00d3fc2f0b4e2b
