### ISSUE TITLE
Can't enter TWRP on liber

### ISSUE THREAD

**Issue by StoneyTBoI** [Evolution-X-AOSP/frameworks_base#470]
As the title suggests, trying to enter boot into TWRP on a Motorola One Fusion + (Liber) doesn't seem to work, while it works on Stock Firmware, Evolution X seems to break TWRP.

If you try `fastboot boot twrp.img`, it sends the required file, tries to boot in TWRP, shows maybe 1-3 seconds of the TWRP splash screen then just turns black.
`adb devices` does show that the device is in "recovery", so you can either hold the power button to restart or do `adb reboot bootloader` to get out of it.

I can't confirm if this is a TWRP issue or a Evo X issue, my original intend was to flash another ROM, but I wanted to make a backup first, just in case.

Which leads me to my question, does Evolution-X have an official backup application, that you can restore if you mess up the installation process of another ROM, so you can rollback onto Evolution X, keeping all your User data, App data and such?

**Comment by joeyhuab** [comment]
This report isn't related to source at all. Report to your device group.
