### ISSUE TITLE
[feature request] Kill foreground app with long back button press

### ISSUE THREAD

**Issue by Phil1pp** [Evolution-X-AOSP/frameworks_base#483]
Hey,

Would it be possible to add the kill action to this rom?
crDroid has some more actions defined which can be selected as customized key action.
[DeviceKeysConstants.java](https://github.com/crdroidandroid/android_lineage-sdk/blob/6939ac6a9272fca818d96b5056e04f7e6bcc010b/sdk/src/java/org/lineageos/internal/util/DeviceKeysConstants.java#L39)
[PhoneWindowManager.java](https://github.com/crdroidandroid/android_frameworks_base/blob/cd32bfb392103dc323f11879dbf0c1be2380834f/services/core/java/com/android/server/policy/PhoneWindowManager.java#L2144)

Maybe you can copy it to this amazing rom.

**Comment by joeyhuab** [comment]
Added here: https://github.com/Evolution-X/frameworks_base/commit/5c834cdb5fa782dcc16b680d1ccbb70004a2b0eb

Will add evolver entries too.
