### ISSUE TITLE
[Feature request]Add haptic effect after back gesture is performed.

### ISSUE THREAD

**Issue by ODtian** [Evolution-X-AOSP/frameworks_base#485]
- device: Mi 11
- rom version: A14 latest build

More detailed, add haptic effect when back gesture is performed/users finger released, just like it will vibrate when back gesture starts or canceled. This feature does exist in some versions(A13), but not in others.

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/packages_apps_Settings/commit/2bb5e2e35162c510c82117a57713c0be93060679

https://github.com/Evolution-X/frameworks_base/commit/56fec4bf88410bea462c42eeb4185ef7d90c721d

it's already there

**Comment by ODtian** [comment]
Not exactly the same, currently no haptic effect when the gesture is done(mean it by finished, or finger released), i.e. back operation is performed. For example, you will get 2-times vibratations when back, one on the begining(swipe and hold) and one on the ending(release). 

Btw, currently you can get 2-times haptic effect, but  when cancelling the gesture, that is one on the begining and one on the cancellation.

Maybe i will post a video to explain it more clearly.
