### ISSUE TITLE
[Feature request] Add haptic effect after back gesture is performed/finished/finger released.

### ISSUE THREAD

**Issue by ODtian** [Evolution-X-AOSP/frameworks_base#486]
Sorry for duplicated issue, but previous issue #485 is closed unexpectedly. I will re- explain what this issue is for and post a video to show it visually.

The exist setting is not exactly the same thing, that one is a global switch whether gesture have haptic effect at all.

Currently no haptic effect when the gesture is done(mean it by finished, or finger released), i.e. back operation is performed.

For example, you will get 2-times vibratations when back, one on the begining(swipe and hold) and one on the ending(release).

Btw, currently you can get 2-times haptic effect, but when cancelling the gesture, that is one on the begining and one on the cancellation.

The video: 
https://github.com/Evolution-X/frameworks_base/assets/40318251/4bd5a2c7-7422-4218-8295-012d816115e9

**Comment by joeyhuab** [comment]
Already resolved on latest Evo.
