### ISSUE TITLE
EdgeBackGestureHandler.java:1332: error:

### ISSUE THREAD

**Issue by Lromdev** [Evolution-X-AOSP/frameworks_base#505]
frameworks/base/packages/SystemUI/src/com/android/systemui/navigationbar/gestural/EdgeBackGestureHandler.java:1332: error: method vibrateBack in class EdgeBackGestureHandler cann
ot be applied to given types;
            vibrateBack(false /* HEAVY_CLICK */);
            ^
  required: no arguments
  found:    boolean
  reason: actual and formal argument lists differ in length
1 error

**Comment by joeyhuab** [comment]
Fixed.

**Comment by Lromdev** [comment]
Thanks!
