### ISSUE TITLE
Data switch tile always shows SIM 2

### ISSUE THREAD

**Issue by QuinceROMs** [Evolution-X-AOSP/frameworks_base#507]
I would like to report a bug. If you have two SIM cards and you switch mobile data between them, the QS data switch tile always shows SIM 2. Switching works, but displaying the current SIM card does not work correctly.

**Comment by joeyhuab** [comment]
Hopefully solved after https://github.com/Evolution-X/frameworks_base/commit/b7a613356a9f55d601da44271671a76cb20e6ef6

**Comment by joeyhuab** [comment]
![Screenshot_20240301-170937_Settings](https://github.com/Evolution-X/frameworks_base/assets/6667815/9bbca1bc-5c31-4d1a-9cea-aa3a52efecfc)

Can confirm fixed.

**Comment by QuinceROMs** [comment]
Yes, everything works fine now. Thank you for the very fast fix. :)
