### ISSUE TITLE
frameworks/base/packages/SystemUI/src/com/android/systemui/biometrics/FingerprintInteractiveToAuthProviderImpl.kt:40:65: error: unresolved reference: config_fingerprintWakeAndUnl ock

### ISSUE THREAD

**Issue by Lromdev** [Evolution-X-AOSP/frameworks_base#512]
frameworks/base/packages/SystemUI/src/com/android/systemui/biometrics/FingerprintInteractiveToAuthProviderImpl.kt:32:8: error: unresolved reference: con
import con.android.internal.R.bool.config_fingerprintWakeAndUnlock
       ^
frameworks/base/packages/SystemUI/src/com/android/systemui/biometrics/FingerprintInteractiveToAuthProviderImpl.kt:40:65: error: unresolved reference: config_fingerprintWakeAndUnl
ock
    private val defaultValue = if (context.resources.getBoolean(config_fingerprintWakeAndUnlock)) {

**Comment by joeyhuab** [comment]
Jeez. Just resync.
