### ISSUE TITLE
Blurred in-app icons in 4.3 EvoX builds

### ISSUE THREAD

**Issue by DjordjeMancic97** [Evolution-X-AOSP/frameworks_base#54]
After checking with multiple app versions and comparing with other devices I came to conclusion that this issue is on rom side. Other users are experiencing too. In-app icons look blurry, here is a example of Instagram bottom navigation bar. Hope you can fix this.
![Screenshot_20200515-181718384 (1)](https://user-images.githubusercontent.com/58264548/82073902-384f9d00-96da-11ea-9b31-61ed4e626dd4.jpg)

**Comment by RealAkito** [comment]
I'll check it out

**Comment by joeyhuab** [comment]
Confirmed as a device specific issue.
