### ISSUE TITLE
[Privacy related] IMEI and other information exposure

### ISSUE THREAD

**Issue by 2220209876** [Evolution-X-AOSP/frameworks_base#70]
[Privacy related] IMEI and other information exposure
Terminal or other software can access IMEi and other information without obtaining ROOT permission
![image](https://user-images.githubusercontent.com/7346652/83408922-02cee180-a446-11ea-91eb-7b8e1a33ee13.png)

Test ROM version : EvolutionX_4.3_raphael-10.0-20200601-0737-OFFICIAL.zip

![image](https://user-images.githubusercontent.com/7346652/83411262-770b8400-a44a-11ea-9f85-f98cf587547e.png)

**Comment by joeyhuab** [comment]
The issue is with MIUI's firmware, similar to the OnePlus issues has NOTHING to do with our ROM.
